/** Printable HTML documents (quotation, receipt, contract, guest list, seating, run sheet). */
import { BRAND } from '@/constants/brand';
import { quoteTotals, lineTotal } from '@/services/quotes';
import type { Contract, Guest, Payment, Project, ProjectEvent, Quotation, SeatingLayout } from '@/types/platform';
import { formatLongDate, formatMoney, formatShortDate, formatTime } from '@/utils/format';

const esc = (s: string) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

const page = (title: string, body: string) => `<!doctype html><html><head><meta charset="utf-8"/><title>${esc(title)}</title>
<style>
  *{box-sizing:border-box} body{font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:#251B18;background:#FFFCF8;margin:32px;font-size:13px}
  h1{font-family:Georgia,'Times New Roman',serif;font-size:24px;color:#681C2A;margin:0 0 4px} h2{font-family:Georgia,'Times New Roman',serif;font-size:15px;margin:22px 0 8px;color:#681C2A}
  .brand{display:flex;justify-content:space-between;align-items:flex-start;border-bottom:2px solid #C8A46B;padding-bottom:14px;margin-bottom:18px}
  .muted{color:#796B64} table{width:100%;border-collapse:collapse} th,td{padding:8px 6px;border-bottom:1px solid #EFE3D5;text-align:left;vertical-align:top}
  th{font-size:11px;color:#796B64} .r{text-align:right} .total td{font-weight:700;font-size:15px;border-top:2px solid #681C2A}
  .box{border:1px solid #E5D6C5;border-radius:10px;padding:12px;margin:10px 0} .grid{display:flex;gap:16px} .grid>div{flex:1}
  .pill{display:inline-block;padding:2px 8px;border-radius:99px;background:#F3E7D2;color:#681C2A;font-size:11px;font-weight:700}
  .sig{margin-top:28px;display:flex;gap:24px} .sig>div{flex:1;border-top:1px solid #C8A46B;padding-top:6px}
  .foot{margin-top:30px;font-size:11px;color:#A39388;text-align:center}
</style></head><body>
<div class="brand"><div><h1>${esc(BRAND.name)} Weddings</h1><div class="muted">Vivah Weddings Pvt. Ltd. · Baneshwor, Kathmandu · PAN 609000111 · ${esc(BRAND.supportEmail)}</div></div><div class="r muted">${esc(title)}<br/>${formatLongDate(new Date().toISOString())}</div></div>
${body}
<div class="foot">Generated by the ${esc(BRAND.name)} app · Payments are held in escrow and released to providers per the agreed schedule.</div>
</body></html>`;

export function quoteHtml(q: Quotation) {
  const totals = quoteTotals(q);
  const rows = q.items
    .map((i) => `<tr><td><b>${esc(i.title)}</b>${i.description ? `<div class="muted">${esc(i.description)}</div>` : ''}</td><td class="r">${i.qty}${i.unit ? ` ${esc(i.unit)}` : ''}</td><td class="r">${formatMoney(i.rate)}</td><td class="r">${formatMoney(lineTotal(i))}</td></tr>`)
    .join('');
  const schedule = q.schedule.map((s) => `<tr><td>${esc(s.label)}</td><td class="r">${s.percent}%</td><td class="r">${formatMoney(Math.round((totals.total * s.percent) / 100))}</td></tr>`).join('');
  return page(
    `Quotation ${q.number} · v${q.version}`,
    `<div class="grid"><div><h2>Prepared for</h2><b>${esc(q.customerName)}</b><div class="muted">${esc(q.city)}</div></div><div><h2>Details</h2>Event: ${formatLongDate(q.eventDate)}<br/>Valid until: ${formatLongDate(q.validUntil)}<br/>From: ${esc(q.fromName)}</div></div>
<h2>Services</h2><table><tr><th>Item</th><th class="r">Qty</th><th class="r">Rate</th><th class="r">Amount</th></tr>${rows}
<tr><td colspan="3" class="r">Subtotal</td><td class="r">${formatMoney(totals.subtotal)}</td></tr>
${totals.discount ? `<tr><td colspan="3" class="r">Package discount</td><td class="r">− ${formatMoney(totals.discount)}</td></tr>` : ''}
${totals.serviceFee ? `<tr><td colspan="3" class="r">Service fee</td><td class="r">${formatMoney(totals.serviceFee)}</td></tr>` : ''}
<tr><td colspan="3" class="r">VAT (${Math.round(q.taxRate * 100)}%)</td><td class="r">${formatMoney(totals.tax)}</td></tr>
<tr class="total"><td colspan="3" class="r">Total</td><td class="r">${formatMoney(totals.total)}</td></tr></table>
<h2>Payment schedule</h2><table>${schedule}</table>
${q.notes ? `<h2>Notes</h2><p>${esc(q.notes)}</p>` : ''}<h2>Terms</h2><p class="muted">${esc(q.terms)}</p>`,
  );
}

export function receiptHtml(payment: Payment, project: Project) {
  const milestone = project.milestones.find((m) => m.id === payment.milestoneId);
  return page(
    `Receipt ${payment.receiptNo}`,
    `<div class="box"><div class="grid"><div><h2>Received from</h2><b>${esc(payment.payerName)}</b><div class="muted">${esc(project.title)} · ${esc(project.code)}</div></div>
<div><h2>Payment</h2>${formatLongDate(payment.at)} ${formatTime(payment.at)}<br/>Method: ${esc(payment.method.replace('_', ' ').toUpperCase())}<br/>Reference: ${esc(payment.reference)}</div></div></div>
<table><tr><th>Description</th><th class="r">Amount</th></tr><tr><td>${esc(milestone?.label ?? 'Payment')}</td><td class="r">${formatMoney(payment.amount)}</td></tr>
<tr class="total"><td class="r">Total received</td><td class="r">${formatMoney(payment.amount)}</td></tr></table>
<p class="muted">Status: <span class="pill">${payment.status}</span>${payment.refunded ? ` · refunded ${formatMoney(payment.refunded)}` : ''}</p>`,
  );
}

export function contractHtml(c: Contract) {
  const sections = c.sections.map((s, i) => `<h2>${i + 1}. ${esc(s.heading)}</h2><p>${esc(s.body)}</p>`).join('');
  const sig = (party: 'customer' | 'provider' | 'platform', label: string, name: string) => {
    const s = c.signatures.find((x) => x.party === party);
    return `<div><b>${esc(label)}</b><br/>${esc(name)}<br/>${s ? `Signed by ${esc(s.name)} on ${formatLongDate(s.at)}` : '<span class="muted">Not signed</span>'}</div>`;
  };
  return page(
    `${c.number} · v${c.version}`,
    `<h1 style="font-size:18px">${esc(c.title)}</h1>${sections}<div class="sig">${sig('customer', 'Customer', c.parties.customer)}${sig('provider', 'Provider', c.parties.provider)}${sig('platform', 'Platform', c.parties.platform)}</div>`,
  );
}

export function guestListHtml(project: Project, guests: Guest[], events: ProjectEvent[]) {
  const head = events.map((e) => `<th>${esc(e.name)}</th>`).join('');
  const rows = guests
    .map((g) => `<tr><td><b>${esc(g.name)}</b>${g.vip ? ' (VIP)' : ''}<div class="muted">${esc(g.category)} · ${g.side}</div></td><td>${esc(g.phone ?? '')}</td>${events.map((e) => {
      const inv = g.invites.find((i) => i.eventId === e.id);
      return `<td>${inv ? `${inv.rsvp.toUpperCase()}${inv.attending ? ` (${inv.attending})` : ''}` : '—'}</td>`;
    }).join('')}<td>${esc(g.dietary.join(', '))}</td></tr>`)
    .join('');
  return page(`Guest list · ${project.title}`, `<table><tr><th>Guest</th><th>Phone</th>${head}<th>Dietary</th></tr>${rows}</table><p class="muted">${guests.length} guests</p>`);
}

export function seatingHtml(project: Project, event: ProjectEvent, layout: SeatingLayout, guests: Guest[]) {
  const tables = layout.elements.filter((e) => e.capacity > 0);
  const blocks = tables
    .map((t) => {
      const seated = guests.filter((g) => g.invites.some((i) => i.eventId === event.id && i.tableId === t.id));
      const count = seated.reduce((s, g) => s + Math.max(1, g.invites.find((i) => i.eventId === event.id)?.attending ?? 1), 0);
      return `<div class="box"><b>${esc(t.label)}</b>${t.vip ? ' <span class="pill">VIP</span>' : ''} <span class="muted">${count}/${t.capacity}</span><ul>${seated.map((g) => `<li>${esc(g.name)}${g.dietary.length ? ` <span class="muted">(${esc(g.dietary.join(', '))})</span>` : ''}</li>`).join('')}</ul></div>`;
    })
    .join('');
  return page(`Seating · ${project.title} · ${event.name}`, `<p>${event.date ? formatLongDate(event.date) : ''} · ${esc(event.venue)}</p><div style="columns:2">${blocks}</div>`);
}

export function runSheetHtml(project: Project, event: ProjectEvent) {
  const rows = event.runSheet.map((r) => `<tr><td><b>${esc(r.time)}</b></td><td>${esc(r.title)}</td><td>${esc(r.owner)}</td><td>${r.status}</td></tr>`).join('');
  const crew = project.bookings
    .filter((b) => b.eventIds.includes(event.id) && b.status !== 'CANCELLED')
    .map((b) => `<tr><td>${esc(b.providerName)}</td><td>${b.assignments.filter((a) => a.eventId === event.id).map((a) => `${esc(a.workerName)} (${esc(a.role)})`).join(', ') || '—'}</td></tr>`)
    .join('');
  return page(`Run sheet · ${project.title} · ${event.name}`, `<p>${event.date ? formatShortDate(event.date) : ''} · ${esc(event.venue)} · ${event.guests} guests</p><table><tr><th>Time</th><th>Cue</th><th>Owner</th><th>Status</th></tr>${rows}</table><h2>Providers & crew</h2><table>${crew}</table>`);
}

/** Printable invitation card (A5) — its own design, without the Vivah letterhead. */
export function invitationHtml(opts: { names: string; message: string; accent: string; background: string; events: ProjectEvent[]; footer?: string }) {
  const events = opts.events
    .map((e) => `<div class="ev"><b>${esc(e.name)}</b><br/>${e.date ? formatLongDate(e.date) : 'Date to be announced'} · ${esc(e.startTime)}<br/><span>${esc(e.venue)}, ${esc(e.city)}</span></div>`)
    .join('');
  return `<!doctype html><html><head><meta charset="utf-8"/><title>${esc(opts.names)}</title><style>
  @page{size:A5;margin:0} body{margin:0;font-family:Georgia,'Times New Roman',serif;background:${opts.background};color:#2b2118}
  .card{margin:24px;padding:36px 28px;border:2px solid ${opts.accent};border-radius:18px;text-align:center;min-height:90vh}
  .om{font-size:28px;color:${opts.accent}} h1{font-size:34px;color:${opts.accent};margin:14px 0} p{white-space:pre-line;font-size:15px;line-height:1.6}
  .ev{margin:14px auto;padding:10px;border-top:1px solid ${opts.accent}33;max-width:320px;font-size:14px} .ev span{color:#6b5b4b}
  .foot{margin-top:22px;font-size:12px;color:#6b5b4b}
  </style></head><body><div class="card"><div class="om">ॐ श्री गणेशाय नमः</div><h1>${esc(opts.names)}</h1><p>${esc(opts.message)}</p>${events}${opts.footer ? `<div class="foot">${esc(opts.footer)}</div>` : ''}</div></body></html>`;
}
